---
language: python
python: "2.7"

env:
  - PLAYBOOK=test.yml

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook tests/$PLAYBOOK -i tests/inventory --syntax-check

  # Initial run
  - ansible-playbook tests/$PLAYBOOK -i tests/inventory --connection=local --become

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook tests/$PLAYBOOK -i tests/inventory --connection=local --become
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: always
  email: false