---
- name: Write Cronjobs
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    month: "{{ item.month | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default('present') }}"
    user: "{{ item.user | default('root') }}"
    when: special_time not in item
  loop: "{{ cronjobs | flatten(levels=1) }}"

- name: Write special time cronjobs
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    special_time: "{{ item.special_time }}"
    state: "{{ item.state | default('present') }}"
    user: "{{ item.user | default('root') }}"
  when: special_time in item
  loop: "{{ cronjobs | flatten(levels=1) }}"
